modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="minecraft_dungeons_mod"
version="2.0.0"
displayName="Minecraft Dungeons Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/osfanbuff63/MinecraftDungeonsMod"
logoFile="logo.png"
authors="osfanbuff63"
description='''
A mod to add items from Minecraft Dungeons into Minecraft!
'''

[[dependencies.minecraft_dungeons_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"

[[dependencies.minecraft_dungeons_mod]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.13]"
    ordering="NONE"
    side="BOTH"



