modLoader="javafml"
loaderVersion="[37,)"
license="MIT License"

[[mods]]
modId="minecraft_dungeons_mod"
version="1.2.0"
displayName="Minecraft Dungeons Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/osfanbuff63/MinecraftDungeonsMod"
logoFile="logo.png"
authors="osfanbuff63"
description='''
A mod to add items from Minecraft Dungeons into Minecraft!
'''

[[dependencies.minecraft_dungeons_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1]"
    ordering="NONE"
    side="BOTH"




