
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package io.github.osfanbuff63.minecraft_dungeons_mod.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.item.Item;

import io.github.osfanbuff63.minecraft_dungeons_mod.item.WonderfulWheatItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.WindHornItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.WhipUnique1Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.WhipItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.TrickbowItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.TotemOfShieldingItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.TotemOfRegenerationItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.TormentQuiverItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.TomeOfDuplicationItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.TastyBoneItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.SwordUnique2Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.SwordUnique1Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.SpearUnique2Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.SpearUnique1Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.SpearItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.SoulScytheUnique2Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.SoulScytheUnique1Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.SoulScytheItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.SoulKnnifeUnique2Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.SoulKnifeUnique1Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.SoulKnifeItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.SoulHealerItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.SoulCrossbowItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.SoulBowItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.SlowbowItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.SicklesUnique2Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.SicklesUnique1Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.SicklesItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.ShortBowItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.ShockPowderItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.ScatterCrossbowItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.RapidCrossbowItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.PowerBowItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.PickaxeSteelUnique1Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.PickaxeMCDItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.MaceUnique2Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.MaceUnique1Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.MaceItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.MCDSwordItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.MCDElytraItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.MCDAxeItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.MCDArrowItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.LoveMedallionItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.LongBowItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.LightFeatherItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.KatanaUnique2Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.KatanaUnique1Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.KatanaItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.IronHideAmuletItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.IceWandItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.HuntingBowItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.HighlanderLongSwordItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.HeavyCrossbowItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.HarvesterItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.HammerUnique2Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.HammerUnique1Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.HammerItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.GongOfWeakeningItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.GlaiveUnique2Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.GlaiveUnique1Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.GlaiveItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.FireworksArrowItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.ExplodingCrossbowUnique1Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.ExplodingCrossbowItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.DoubleAxeUnique2Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.DoubleAxeUnique1Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.DoubleAxeItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.DeathCapMushroomItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.DaggersUnique3Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.DaggersUnique2Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.DaggersUnique1Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.DaggersItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.CutlassUnique3Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.CutlassUnique2Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.CutlassUnique1Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.CutlassItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.CrossbowUnique2Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.CrossbowUnique1Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.CorruptedSeedsItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.CorruptedBeaconItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.ClaymoreUnique3Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.ClaymoreUnique2Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.ClaymoreUnique1Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.ClaymoreItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.BowUnique2Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.BowUnique1Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.BootsOfSwiftnessItem;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.AxeUnique2Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.item.AxeUnique1Item;
import io.github.osfanbuff63.minecraft_dungeons_mod.MinecraftDungeonsModMod;

public class MinecraftDungeonsModModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, MinecraftDungeonsModMod.MODID);
	public static final RegistryObject<Item> TASTY_BONE = REGISTRY.register("tasty_bone", () -> new TastyBoneItem());
	public static final RegistryObject<Item> MCD_ARROW = REGISTRY.register("mcd_arrow", () -> new MCDArrowItem());
	public static final RegistryObject<Item> EXPLODING_CROSSBOW = REGISTRY.register("exploding_crossbow", () -> new ExplodingCrossbowItem());
	public static final RegistryObject<Item> HEAVY_CROSSBOW = REGISTRY.register("heavy_crossbow", () -> new HeavyCrossbowItem());
	public static final RegistryObject<Item> HUNTING_BOW = REGISTRY.register("hunting_bow", () -> new HuntingBowItem());
	public static final RegistryObject<Item> LONG_BOW = REGISTRY.register("long_bow", () -> new LongBowItem());
	public static final RegistryObject<Item> POWER_BOW = REGISTRY.register("power_bow", () -> new PowerBowItem());
	public static final RegistryObject<Item> RAPID_CROSSBOW = REGISTRY.register("rapid_crossbow", () -> new RapidCrossbowItem());
	public static final RegistryObject<Item> SCATTER_CROSSBOW = REGISTRY.register("scatter_crossbow", () -> new ScatterCrossbowItem());
	public static final RegistryObject<Item> SHORT_BOW = REGISTRY.register("short_bow", () -> new ShortBowItem());
	public static final RegistryObject<Item> SLOWBOW = REGISTRY.register("slowbow", () -> new SlowbowItem());
	public static final RegistryObject<Item> SOUL_BOW = REGISTRY.register("soul_bow", () -> new SoulBowItem());
	public static final RegistryObject<Item> SOUL_CROSSBOW = REGISTRY.register("soul_crossbow", () -> new SoulCrossbowItem());
	public static final RegistryObject<Item> TRICKBOW = REGISTRY.register("trickbow", () -> new TrickbowItem());
	public static final RegistryObject<Item> MCD_AXE = REGISTRY.register("mcd_axe", () -> new MCDAxeItem());
	public static final RegistryObject<Item> CLAYMORE = REGISTRY.register("claymore", () -> new ClaymoreItem());
	public static final RegistryObject<Item> CUTLASS = REGISTRY.register("cutlass", () -> new CutlassItem());
	public static final RegistryObject<Item> DAGGERS = REGISTRY.register("daggers", () -> new DaggersItem());
	public static final RegistryObject<Item> DOUBLE_AXE = REGISTRY.register("double_axe", () -> new DoubleAxeItem());
	public static final RegistryObject<Item> GLAIVE = REGISTRY.register("glaive", () -> new GlaiveItem());
	public static final RegistryObject<Item> HAMMER = REGISTRY.register("hammer", () -> new HammerItem());
	public static final RegistryObject<Item> HIGHLANDER_LONG_SWORD = REGISTRY.register("highlander_long_sword", () -> new HighlanderLongSwordItem());
	public static final RegistryObject<Item> KATANA = REGISTRY.register("katana", () -> new KatanaItem());
	public static final RegistryObject<Item> MACE = REGISTRY.register("mace", () -> new MaceItem());
	public static final RegistryObject<Item> PICKAXE_MCD = REGISTRY.register("pickaxe_mcd", () -> new PickaxeMCDItem());
	public static final RegistryObject<Item> SICKLES = REGISTRY.register("sickles", () -> new SicklesItem());
	public static final RegistryObject<Item> SOUL_KNIFE = REGISTRY.register("soul_knife", () -> new SoulKnifeItem());
	public static final RegistryObject<Item> SOUL_SCYTHE = REGISTRY.register("soul_scythe", () -> new SoulScytheItem());
	public static final RegistryObject<Item> SPEAR = REGISTRY.register("spear", () -> new SpearItem());
	public static final RegistryObject<Item> MCD_SWORD = REGISTRY.register("mcd_sword", () -> new MCDSwordItem());
	public static final RegistryObject<Item> WHIP = REGISTRY.register("whip", () -> new WhipItem());
	public static final RegistryObject<Item> IRON_HIDE_AMULET = REGISTRY.register("iron_hide_amulet", () -> new IronHideAmuletItem());
	public static final RegistryObject<Item> BOOTS_OF_SWIFTNESS = REGISTRY.register("boots_of_swiftness", () -> new BootsOfSwiftnessItem());
	public static final RegistryObject<Item> CORRUPTED_BEACON = REGISTRY.register("corrupted_beacon", () -> new CorruptedBeaconItem());
	public static final RegistryObject<Item> CORRUPTED_SEEDS = REGISTRY.register("corrupted_seeds", () -> new CorruptedSeedsItem());
	public static final RegistryObject<Item> DEATH_CAP_MUSHROOM = REGISTRY.register("death_cap_mushroom", () -> new DeathCapMushroomItem());
	public static final RegistryObject<Item> MCD_ELYTRA = REGISTRY.register("mcd_elytra", () -> new MCDElytraItem());
	public static final RegistryObject<Item> FIREWORKS_ARROW = REGISTRY.register("fireworks_arrow", () -> new FireworksArrowItem());
	public static final RegistryObject<Item> GONG_OF_WEAKENING = REGISTRY.register("gong_of_weakening", () -> new GongOfWeakeningItem());
	public static final RegistryObject<Item> HARVESTER = REGISTRY.register("harvester", () -> new HarvesterItem());
	public static final RegistryObject<Item> ICE_WAND = REGISTRY.register("ice_wand", () -> new IceWandItem());
	public static final RegistryObject<Item> LIGHT_FEATHER = REGISTRY.register("light_feather", () -> new LightFeatherItem());
	public static final RegistryObject<Item> LOVE_MEDALLION = REGISTRY.register("love_medallion", () -> new LoveMedallionItem());
	public static final RegistryObject<Item> SHOCK_POWDER = REGISTRY.register("shock_powder", () -> new ShockPowderItem());
	public static final RegistryObject<Item> SOUL_HEALER = REGISTRY.register("soul_healer", () -> new SoulHealerItem());
	public static final RegistryObject<Item> TOME_OF_DUPLICATION = REGISTRY.register("tome_of_duplication", () -> new TomeOfDuplicationItem());
	public static final RegistryObject<Item> TORMENT_QUIVER = REGISTRY.register("torment_quiver", () -> new TormentQuiverItem());
	public static final RegistryObject<Item> TOTEM_OF_REGENERATION = REGISTRY.register("totem_of_regeneration", () -> new TotemOfRegenerationItem());
	public static final RegistryObject<Item> TOTEM_OF_SHIELDING = REGISTRY.register("totem_of_shielding", () -> new TotemOfShieldingItem());
	public static final RegistryObject<Item> WIND_HORN = REGISTRY.register("wind_horn", () -> new WindHornItem());
	public static final RegistryObject<Item> WONDERFUL_WHEAT = REGISTRY.register("wonderful_wheat", () -> new WonderfulWheatItem());
	public static final RegistryObject<Item> AXE_UNIQUE_1 = REGISTRY.register("axe_unique_1", () -> new AxeUnique1Item());
	public static final RegistryObject<Item> AXE_UNIQUE_2 = REGISTRY.register("axe_unique_2", () -> new AxeUnique2Item());
	public static final RegistryObject<Item> CLAYMORE_UNIQUE_1 = REGISTRY.register("claymore_unique_1", () -> new ClaymoreUnique1Item());
	public static final RegistryObject<Item> CLAYMORE_UNIQUE_2 = REGISTRY.register("claymore_unique_2", () -> new ClaymoreUnique2Item());
	public static final RegistryObject<Item> CLAYMORE_UNIQUE_3 = REGISTRY.register("claymore_unique_3", () -> new ClaymoreUnique3Item());
	public static final RegistryObject<Item> CUTLASS_UNIQUE_1 = REGISTRY.register("cutlass_unique_1", () -> new CutlassUnique1Item());
	public static final RegistryObject<Item> CUTLASS_UNIQUE_2 = REGISTRY.register("cutlass_unique_2", () -> new CutlassUnique2Item());
	public static final RegistryObject<Item> CUTLASS_UNIQUE_3 = REGISTRY.register("cutlass_unique_3", () -> new CutlassUnique3Item());
	public static final RegistryObject<Item> DAGGERS_UNIQUE_1 = REGISTRY.register("daggers_unique_1", () -> new DaggersUnique1Item());
	public static final RegistryObject<Item> DAGGERS_UNIQUE_2 = REGISTRY.register("daggers_unique_2", () -> new DaggersUnique2Item());
	public static final RegistryObject<Item> DAGGERS_UNIQUE_3 = REGISTRY.register("daggers_unique_3", () -> new DaggersUnique3Item());
	public static final RegistryObject<Item> DOUBLE_AXE_UNIQUE_1 = REGISTRY.register("double_axe_unique_1", () -> new DoubleAxeUnique1Item());
	public static final RegistryObject<Item> DOUBLE_AXE_UNIQUE_2 = REGISTRY.register("double_axe_unique_2", () -> new DoubleAxeUnique2Item());
	public static final RegistryObject<Item> GLAIVE_UNIQUE_1 = REGISTRY.register("glaive_unique_1", () -> new GlaiveUnique1Item());
	public static final RegistryObject<Item> GLAIVE_UNIQUE_2 = REGISTRY.register("glaive_unique_2", () -> new GlaiveUnique2Item());
	public static final RegistryObject<Item> HAMMER_UNIQUE_1 = REGISTRY.register("hammer_unique_1", () -> new HammerUnique1Item());
	public static final RegistryObject<Item> HAMMER_UNIQUE_2 = REGISTRY.register("hammer_unique_2", () -> new HammerUnique2Item());
	public static final RegistryObject<Item> KATANA_UNIQUE_1 = REGISTRY.register("katana_unique_1", () -> new KatanaUnique1Item());
	public static final RegistryObject<Item> KATANA_UNIQUE_2 = REGISTRY.register("katana_unique_2", () -> new KatanaUnique2Item());
	public static final RegistryObject<Item> MACE_UNIQUE_1 = REGISTRY.register("mace_unique_1", () -> new MaceUnique1Item());
	public static final RegistryObject<Item> MACE_UNIQUE_2 = REGISTRY.register("mace_unique_2", () -> new MaceUnique2Item());
	public static final RegistryObject<Item> PICKAXE_STEEL_UNIQUE_1 = REGISTRY.register("pickaxe_steel_unique_1",
			() -> new PickaxeSteelUnique1Item());
	public static final RegistryObject<Item> SICKLES_UNIQUE_1 = REGISTRY.register("sickles_unique_1", () -> new SicklesUnique1Item());
	public static final RegistryObject<Item> SICKLES_UNIQUE_2 = REGISTRY.register("sickles_unique_2", () -> new SicklesUnique2Item());
	public static final RegistryObject<Item> SOUL_KNIFE_UNIQUE_1 = REGISTRY.register("soul_knife_unique_1", () -> new SoulKnifeUnique1Item());
	public static final RegistryObject<Item> SOUL_KNNIFE_UNIQUE_2 = REGISTRY.register("soul_knnife_unique_2", () -> new SoulKnnifeUnique2Item());
	public static final RegistryObject<Item> SOUL_SCYTHE_UNIQUE_1 = REGISTRY.register("soul_scythe_unique_1", () -> new SoulScytheUnique1Item());
	public static final RegistryObject<Item> SOUL_SCYTHE_UNIQUE_2 = REGISTRY.register("soul_scythe_unique_2", () -> new SoulScytheUnique2Item());
	public static final RegistryObject<Item> SPEAR_UNIQUE_1 = REGISTRY.register("spear_unique_1", () -> new SpearUnique1Item());
	public static final RegistryObject<Item> SPEAR_UNIQUE_2 = REGISTRY.register("spear_unique_2", () -> new SpearUnique2Item());
	public static final RegistryObject<Item> SWORD_UNIQUE_1 = REGISTRY.register("sword_unique_1", () -> new SwordUnique1Item());
	public static final RegistryObject<Item> SWORD_UNIQUE_2 = REGISTRY.register("sword_unique_2", () -> new SwordUnique2Item());
	public static final RegistryObject<Item> WHIP_UNIQUE_1 = REGISTRY.register("whip_unique_1", () -> new WhipUnique1Item());
	public static final RegistryObject<Item> BOW_UNIQUE_1 = REGISTRY.register("bow_unique_1", () -> new BowUnique1Item());
	public static final RegistryObject<Item> BOW_UNIQUE_2 = REGISTRY.register("bow_unique_2", () -> new BowUnique2Item());
	public static final RegistryObject<Item> CROSSBOW_UNIQUE_1 = REGISTRY.register("crossbow_unique_1", () -> new CrossbowUnique1Item());
	public static final RegistryObject<Item> CROSSBOW_UNIQUE_2 = REGISTRY.register("crossbow_unique_2", () -> new CrossbowUnique2Item());
	public static final RegistryObject<Item> EXPLODING_CROSSBOW_UNIQUE_1 = REGISTRY.register("exploding_crossbow_unique_1",
			() -> new ExplodingCrossbowUnique1Item());
}
