name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome! Thanks for creating your first issue - we'll be taking a look at it shortly!'
        pr-message: 'Welcome! Thanks for creating your first pull request- we'll be taking a look at it shortly!'
